FROM oven/bun:1

WORKDIR /app
ARG DATABASE_URL
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate
RUN echo ${DATABASE_URL}
RUN bun run build

EXPOSE 8080

CMD ["bun", "run", "start:web"]

